[mcp_servers.filesystem]
args = [
    'C:\Users\V0141351\.npm-global\node_modules\@modelcontextprotocol\server-filesystem\dist\index.js',
    'd:\wzy\Python\vivo-project',
]
command = "node"

[mcp_servers.puppeteer]
args = ['C:\Users\V0141351\.npm-global\node_modules\@modelcontextprotocol\server-puppeteer\dist\index.js']
command = "node"
