async page => {
  await page.setViewportSize({ width: 1365, height: 900 });
  await page.goto('http://localhost:8518/?scenario=failure');
  await page.getByRole('button', { name: '查询', exact: true }).click();
  await page.getByText('蒸镀材料检验数据暂时无法读取，请稍后重新查询。', { exact: true }).waitFor();
  if (await page.getByTestId('stDataFrame').count()) throw new Error('Failure shows stale table');
  const body = await page.locator('body').innerText();
  if (/private SQL|connection details|Traceback|管理员|admin=true/.test(body)) throw new Error('Failure leaks internals');
  await page.goto('http://localhost:8518/');
  const product = page.getByTestId('stMultiSelect').getByRole('combobox');
  await product.click();
  await page.getByRole('option', { name: 'M626', exact: true }).click();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '查询', exact: true }).click();
  const table = page.getByTestId('stDataFrame');
  await table.waitFor();
  await page.getByText('共 205 条记录 · 左右滚动查看全部测点和检验结果', { exact: true }).waitFor();
  if (await page.getByRole('spinbutton', { name: '页码', exact: true }).count()) throw new Error('Manual pagination remains');
  await page.screenshot({ path: 'native-controlled-full-result.png', fullPage: true });
  await product.focus();
  await product.press('Backspace');
  await product.click();
  await page.getByRole('option', { name: 'M678', exact: true }).click();
  await page.keyboard.press('Escape');
  await page.getByText('请选择检验日期范围和产品型号并点击“查询”。', { exact: true }).waitFor();
  if (await table.count()) throw new Error('Old product rows remain');
  await page.getByRole('button', { name: '查询', exact: true }).click();
  await table.waitFor();
  await page.getByText('共 1 条记录 · 左右滚动查看全部测点和检验结果', { exact: true }).waitFor();
  await product.focus();
  await product.press('Backspace');
  await product.click();
  await page.getByRole('option', { name: 'Z571', exact: true }).click();
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '查询', exact: true }).click();
  await page.getByText('没有符合筛选条件的记录，请调整筛选条件。', { exact: true }).waitFor();
  if (await table.count()) throw new Error('Common rows shown for unmatched product');
  if (await page.locator('[data-testid="stMultiSelect"]').count() !== 1) throw new Error('Extra filters remain');
  if (await page.locator('[data-testid="stException"]').count()) throw new Error('Streamlit exception');
  return { status: 'passed', source: 'controlled data port', scenarios: ['failure', 'recovery', 'full-result', 'exact-product', 'exclude-common', 'empty'] };
}
