async page => {
  const output = "D:/wzy/Python/vivo-project/output/test-results/monitor-excel";
  const base = "http://localhost:8516/";
  const errors = [];
  page.on("console", message => {
    const text = message.text();
    const telemetry = (message.location().url || "").includes("data.streamlit.io") ||
      text.includes("metrics config") || text.includes("metrics tracking");
    if (message.type() === "error" && !telemetry) errors.push(text);
  });
  const oosQuery = () => page.locator(".st-key-btn_monitor_query_submit button:visible").first();
  const cpkQuery = () => page.locator(".st-key-cpk_monitor_query_submit button:visible").first();
  const expectText = text => page.getByText(text, { exact: true }).waitFor({ timeout: 60000 });
  const absent = text => page.getByText(text, { exact: true }).waitFor({ state: "hidden", timeout: 10000 });
  await page.goto(base);
  await cpkQuery().waitFor({ timeout: 60000 });
  await absent("超规趋势");
  await absent("CPK 汇总表");
  await absent("数据最后更新时间（管理员）");
  await expectText("Fixture week OOS: 0");
  await oosQuery().click();
  await expectText("超规趋势");
  await expectText("Fixture week OOS: 1");
  await expectText("Fixture year OOS: 101");
  await expectText("Fixture closed preserved: True");
  await absent("CPK 汇总表");
  await oosQuery().click();
  await expectText("Fixture year OOS: 101");
  await cpkQuery().click();
  await expectText("CPK 汇总表");
  await expectText("Fixture CPK warning total: 8");
  await absent("数据最后更新时间（管理员）");
  await page.screenshot({ path: `${output}/regular.png`, fullPage: true });
  await page.locator(".st-key-fixture_edit_excel button:visible").click();
  await expectText("Fixture Excel decorated: True");
  await page.locator(".st-key-fixture_refresh_cache button:visible").click();
  await absent("超规趋势");
  await absent("CPK 汇总表");
  await oosQuery().click();
  await expectText("Fixture week OOS: 0");
  await expectText("Fixture year OOS: 100");
  await expectText("Fixture closed preserved: True");
  await page.goto(`${base}?admin=true`);
  await oosQuery().click();
  await expectText("数据最后更新时间（管理员）");
  await cpkQuery().click();
  await expectText("CPK 汇总表");
  await page.screenshot({ path: `${output}/admin.png`, fullPage: true });
  await page.setViewportSize({ width: 768, height: 900 });
  const overflow = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, client: document.documentElement.clientWidth }));
  if (overflow.scroll > overflow.client + 2) throw new Error(`Horizontal overflow: ${JSON.stringify(overflow)}`);
  await page.screenshot({ path: `${output}/admin-768.png`, fullPage: true });
  await page.locator(".st-key-fixture_edit_cpk button:visible").click();
  await expectText("Fixture CPK Excel decorated: True");
  await page.locator(".st-key-fixture_refresh_cache button:visible").click();
  await absent("CPK 汇总表");
  await cpkQuery().click();
  await expectText("Fixture CPK warning total: 6");
  await expectText("Fixture CPK history preserved: True");
  await expectText("CPK 预警趋势");
  if (errors.length) throw new Error(`Browser console errors: ${errors.join(" | ")}`);
  return "Excel-only queries, idempotence, Flag refresh, closed periods, CPK and admin visibility passed";
}
