# 数据加载相关的参数
data_source:
  product_code: "M626"

  # 4. defect_group
  target_defect_groups:
    - "Array_Line"
    - "Array_Pixel"
    - "Array_Mura"
    - "OLED_Mura"
    
  work_order_types:
    - "ESLC" # 量产
    - "P" # 量产
    - "LCFG" # 量产返工
    - "SLCFG" # 试量产返工
    - "SYZLC" # 实验转量产

# 本地文件读取：根目录并不是resources，而是resources/"产品号"
paths:
  static_warning_lines: 
    file_name: 'M626_入库不良率规格.xlsx'
    sheet_name: 'Sheet1'
  
  rate_override_config:
    file_name: "M626_override_rates.xlsx"
    sheet_name: "Sheet1"
    
  mwd_override_config:
    file_name: "M626_趋势图人工修正.xlsx"

# 数据处理相关的参数
processing:
  use_local_snapshot: True
  snapshot_path: 'data/snapshot_M626.parquet'
  
  defect_capping:
    enable: True
  
  # 3. lot阵列投入时间
  array_input_time:
    custom_times:

  # 5. defect_code倍率调节
  defect_multipliers:
    # Array_Line
    S向单暗线: 0.9
    # Array_Pixel
    # Array_Mura
    'S向ELA Mura': 0
    'G向ELA Mura': 0
    '白画面黑斑Mura': 0.8
    # OLED_Mura
    '彩斑Mura': 0.4
    'S向边缘Mura': 0.6

  # 6. sheet/lot波动调节
  sheet_hotspot_config: 
    enable: True
    random_seed: 2025
    hide_hotspot_config: {
        'fluctuation_sheet': 0.2,  
        'fluctuation_lot': 0.2,
    }

# SPC 参数规格覆盖配置
# 用于手动调整特定产品-站点-参数的规格限制
spc_spec_override:
  - prod_code: "M626"
    step_id: "1L650"
    param_name: "CD1"
    ucl: 5.45
