# 数据加载相关的参数
data_source:
  product_code: "M626"

  # 4. defect_group
  target_defect_groups:
    - "Array_Line"
    - "Array_Pixel"
    - "OLED_Mura"
    
  work_order_types:
    - "ESLC" # 量产
    - "P" # 量产
    - "LCFG" # 量产返工
    - "SLCFG" # 试量产返工
    - "SYZLC" # 实验转量产

# 本地文件读取
paths:
  static_warning_lines: 
    file_name: 'M626_入库不良率规格.xlsx'
    sheet_name: 'Sheet1'

# 数据处理相关的参数
processing:
  use_local_snapshot: True
  snapshot_path: 'data/snapshot_M626.parquet'
  
  defect_capping:
    enable: True

  # 1. Group 级修正配置
  group_monthly_values:
    Array_Line:
      "2026-01": 0.0096

  group_weekly_values:
    Array_Line:
      "2026-W04": 0.0105
      "2026-W05": 0.0092
      "2026-W06": 0.0104
    Array_Pixel:
      "2026-W05": 0.0107
      "2026-W06": 0.0116
    OLED_Mura:
      "2026-W05": 0.0037

  group_daily_values:

  # 2. Code 级修正配置
  code_monthly_values:

  code_weekly_values:
    "暗点":
      "2026-W05": 0.0021
  
  # 3. lot阵列投入时间
  array_input_time:
    custom_times:

  # 5. defect_code倍率调节
  defect_multipliers:
    '彩斑Mura': 0.3
    'S向棱形彩色带状Mura': 0.3

  # 6. Mapping集中性调节
  mapping_hotspot_script:
    - enable: true
      target_code: '彩斑Mura'       
      target_batch_index: 'oldest'    
      mode: 'multiplicative'          
      hotspot_multiplier: 0.3
      normal_multiplier: 1.5
      hotspot_rules:
        - { type: 'row', value: ['1E','2A','2B'] } 

    - enable: true
      target_code: 'S向边缘Mura'
      target_batch_index: 'oldest'
      mode: 'additive' 
      hotspot_adder: 2
      normal_multiplier_in_add_mode: 0
      hotspot_rules:
        - { 
            type: 'position', 
            value: [
              ['1A', 'J0'], ['1A', 'K0'], ['1A', 'L0'], ['1B', 'J0'],
              ['1B', 'K0'], ['1B', 'L0'], ['2B', 'F0'], ['2B', 'G0'],
              ['1B', 'P0'], ['1B', 'S0'], ['1D', 'A0'], ['2B', 'B0'],
              ['1A', 'S0'], ['2B', 'A0']
            ]
          }

  # 7. sheet/lot波动调节
  sheet_hotspot_config: 
    enable: True
    random_seed: 2025
    hide_hotspot_config: {
        'fluctuation_sheet': 0.2,  
        'fluctuation_lot': 0.2,
    }
