# M673为高PPI产品，Array段良率较低

# 数据加载相关的参数
data_source:
  product_code: "M673"

# 本地文件读取
paths:
  static_warning_lines: 
    file_name: 'M673_入库不良率规格.xlsx'
    sheet_name: 'Sheet1'

  rate_override_config:
    file_name: "M673_override_rates.xlsx"
    sheet_name: "Sheet1"

  mwd_override_config:
    file_name: "M673_趋势图人工修正.xlsx"

# 数据处理相关的参数
processing:
  use_local_snapshot: True
  snapshot_path: 'data/snapshot_M673.parquet'
  
  defect_capping:
    enable: True

  defect_multipliers:
    # Array_Line
    'S向亮线': 0.6
    'G向单暗线': 0.5
    # Array_Pixel
    '暗点': 2
    '群暗点': 1.5
    '群亮点': 2
    # Array_Mura
    'S向ELA Mura': 0
    'G向ELA Mura': 0
    'G向带状Mura': 0
    # OLED_Mura
    '通道间短路': 0.5
  
  sheet_hotspot_config: 
    enable: True
    random_seed: 2025
    hide_hotspot_config: {
        'fluctuation_sheet': 0.2,  
        'fluctuation_lot': 0.2,
    }
