# 数据加载相关的参数
data_source:
  product_code: "M678"

  # 4. defect_group
  target_defect_groups:
    - "Array_Line"
    - "Array_Pixel"
    - "OLED_Mura"
    
  work_order_types:
    - "ESLC" # 量产
    - "P" # 量产
    - "LCFG" # 量产返工
    - "SLCFG" # 试量产返工
    - "SYZLC" # 实验转量产

# 本地文件读取
paths:
  static_warning_lines: 
    file_name: 'M678_入库不良率规格.xlsx'
    sheet_name: 'Sheet1'

  rate_override_config:
    file_name: "M678_override_rates.xlsx"
    sheet_name: "Sheet1"

  mwd_override_config:
    file_name: "M678_趋势图人工修正.xlsx"

# 数据处理相关的参数
processing:
  use_local_snapshot: True
  snapshot_path: 'data/snapshot_M678.parquet'
  
  defect_capping:
    enable: True

  # 3. lot阵列投入时间
  array_input_time:
    custom_times:
      # 高发sheet_id：共计 5 个
      L3MR58E5C08: '20250805'
      L3MR58E5C03: '20250805' 
      L3MR58E5C10: '20250805'
      L3MR58E5C26: '20250805'
      L3MR58E5C04: '20250805'

  # 5. defect_code倍率调节
  defect_multipliers:
    # Array_Line
    'S向亮线': 0.4
    'G向单亮线': 0.5
    # Array_Pixel
    '暗点': 0.7
    'G3亮点': 0.5
    # OLED_Mura
    '彩斑Mura': 0.3

  # 6. Mapping集中性调节
  mapping_hotspot_script:
    - enable: true
      target_code: 'S向单暗线'       
      target_batch_index: 'oldest'    
      mode: 'multiplicative'          
      hotspot_multiplier: 1.3
      normal_multiplier: 0.7
      hotspot_rules:
        - { type: 'row', value: ['2E', '1A'] }
        - { type: 'col', value: ['A0', 'B0', 'S0'] }

  sheet_hotspot_config: 
      enable: True
      random_seed: 2025
      hide_hotspot_config: {
          'fluctuation_sheet': 0.2,  
          'fluctuation_lot': 0.2,
      }