# Z517同M678一致、

# 数据加载相关的参数
data_source:
  product_code: "Z517"

# 本地文件读取
paths:
  static_warning_lines: 
    file_name: '入库不良率规格.xlsx'
    sheet_name: 'Z517'

  rate_override_config:
    file_name: "override_rates.xlsx"
    sheet_name: "Z517"

  yield_modifier_config:
    file_name: "入库良率修饰表.xlsx"

# 数据处理相关的参数
processing:
  use_local_snapshot: True
  snapshot_path: 'data/snapshot_Z517.parquet'

  mapping_layout:
    row_labels:
      - '1A'
      - '1B'
      - '1C'
      - '1D'
      - '2A'
      - '2B'
      - '2C'
      - '2D'
    column_labels:
      - 'A0'
      - 'B0'
      - 'C0'
      - 'D0'
      - 'E0'
      - 'F0'
      - 'G0'
      - 'H0'
      - 'J0'
      - 'K0'
      - 'L0'
  
  defect_capping:
    enable: True
  
    # 5. defect_code倍率调节
  defect_multipliers:

  sheet_hotspot_config: 
    enable: True
    random_seed: 2025
    hide_hotspot_config: {
        'fluctuation_sheet': 0.2,  
        'fluctuation_lot': 0.2,
    }
