# Z571同M678一致、

# 数据加载相关的参数
data_source:
  product_code: "Z571"

# 本地文件读取
paths:
  static_warning_lines: 
    file_name: '入库不良率规格.xlsx'
    sheet_name: 'Z571'

  rate_override_config:
    file_name: "override_rates.xlsx"
    sheet_name: "Z571"

  yield_modifier_config:
    file_name: "入库良率修饰表.xlsx"

# 数据处理相关的参数
processing:
  use_local_snapshot: True
  snapshot_path: 'data/snapshot_Z571.parquet'
  
  defect_capping:
    enable: True
  
    # 5. defect_code倍率调节
  defect_multipliers:
    # Array_Line
    'S向亮线': 0.7
    'G向单亮线': 0.5
    'G向单暗线': 0.8
    # # Array_Pixel
    # Array_Mura
    'S向ELA Mura': 0
    'G向ELA Mura': 0
    'G向带状Mura': 0
    # OLED_Mura
    '彩斑Mura': 0.7
    # TP
    'TP复测NG': 2
    'Short Test NG': 0.2

  sheet_hotspot_config: 
    enable: True
    random_seed: 2025
    hide_hotspot_config: {
        'fluctuation_sheet': 0.2,  
        'fluctuation_lot': 0.2,
    }
