[theme]
# 1. 基础模式
base = "light"

# 2. 主色调 (Primary Color) 
# 对应你 HTML 中的 Sky-500 (#0ea5e9) - 用于按钮、选中框、进度条
primaryColor = "#0ea5e9"

# 3. 背景颜色 (Background Color)
# 对应 HTML 背景的淡蓝色 (#f0f9ff - Sky-50) 或白色
backgroundColor = "#f8fafc"

# 4. 侧边栏背景颜色 (Secondary Background Color)
# 这样不仅侧边栏会有淡淡的区分度，下拉框也会恢复清爽的浅色！
secondaryBackgroundColor = "#f1f5f9"

# 5. 文本颜色 (Text Color)
# 对应 HTML 中的 Slate-700 (#334155)
textColor = "#334155"

# 6. 字体
font = "sans serif"

[server]
# 禁止 Streamlit 自动打开浏览器 (因为我们要让脚本打开门户页面)
headless = true

[client]
# 强制开启开发者工具栏 (恢复 Rerun 按钮)
toolbarMode = "developer"
# 允许在前端显示详细的错误堆栈
showErrorDetails = true